# Generated by Django 5.2.8 on 2025-11-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_payment_reference_order_payment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event_id"], name="orders_webh_event_i_c4bcae_idx"
                    ),
                    models.Index(
                        fields=["processed"], name="orders_webh_process_d0204f_idx"
                    ),
                ],
            },
        ),
    ]
