# Generated by Django 5.2.8 on 2025-11-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_webhookcleanuplog_dailysalesreport_lowstockalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
