# Generated by Django 5.2.8 on 2025-11-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_webhookevent_archived_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("args", models.JSONField()),
                ("kwargs", models.JSONField()),
                ("exception", models.TextField()),
                ("traceback", models.TextField()),
                ("failed_at", models.DateTimeField(auto_now_add=True)),
                ("retried", models.BooleanField(default=False)),
                ("retried_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-failed_at"],
                "indexes": [
                    models.Index(
                        fields=["task_name"], name="orders_fail_task_na_9e18e2_idx"
                    ),
                    models.Index(
                        fields=["retried"], name="orders_fail_retried_19683c_idx"
                    ),
                ],
            },
        ),
    ]
